apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrimony-backend
  namespace: matrimony-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matrimony-backend
  template:
    metadata:
      labels:
        app: matrimony-backend
    spec:
      containers:
      - name: matrimony-backend
        image: your-dockerhub-username/matrimony-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/matrimony"
