apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: matrimony-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Internal access only (Use Ingress)



