apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: matrimony-namespace  # Add this line
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devshubh2204/matrimony-meet-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/matrimony"

