apiVersion: v1
kind: Service
metadata:
  name: php-backend-service
  namespace: matrimony-app
spec:
  type: NodePort
  selector:
    app: matrimony-backend  # Fixed selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Match Deployment's containerPort
      nodePort: 32000


