pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "yourdockerhub/matrimony-backend:latest"
        K8S_NAMESPACE = "matrimony-namespace"  // Define namespace
    }
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/your-repo/matrimony_meet.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE ./backend'
            }
        }
        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub', url: '']) {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployment/kubernetes/namespace.yaml'
                sh 'kubectl apply -f deployment/kubernetes/deployment.yaml -n $K8S_NAMESPACE'
                sh 'kubectl apply -f deployment/kubernetes/service.yaml -n $K8S_NAMESPACE'
                sh 'kubectl apply -f deployment/kubernetes/ingress.yaml -n $K8S_NAMESPACE'  // Apply Ingress
            }
        }
        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -n $K8S_NAMESPACE'
                sh 'kubectl get svc -n $K8S_NAMESPACE'
                sh 'kubectl get ingress -n $K8S_NAMESPACE'  // Verify Ingress
            }
        }
    }
}
